name:  Release NodeJS app # Name of the workflow

# On a push to the branch named master
on:
  push:
    branches:
      - main
    paths:
        - 'express-app/**'
        - '.github/workflows/express-app.yml'

# Job called build runs-on ubuntu-latest
jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
  
      # We need to login so we can later push the image without issues. 
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      # Build and push
      - name: Build and push scratch
        uses: docker/build-push-action@v5
        with:
          context: express-app
          file: express-app/Dockerfile
          push: true
          tags: illuteracy/express-app:latest
  